name: "Continuous Deployment"
on:
  push:
    branches:
      - dev
jobs:
  #  push_to_registry:
  #    name: Push Docker image to GitHub Packages
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Set up JDK 17
  #        uses: actions/setup-java@v2
  #        with:
  #          java-version: 17
  #          distribution: 'adopt'
  #
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #        with:
  #          ref: dev
  #
  #      - name: Authorize gradlew script
  #        run: chmod +x ./gradlew
  #
  #      - name: Build with gradle
  #        env:
  #          USERNAME: ${{ secrets.USERNAME }}
  #          TOKEN: ${{ secrets.TOKEN }}
  #        run: ./gradlew build --info
  #
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v2
  #
  #      - name: Login to GitHub Container Registry
  #        uses: docker/login-action@v1
  #        with:
  #          registry: ghcr.io
  #          username: ${{ secrets.USERNAME }}
  #          password: ${{ secrets.TOKEN }}
  #
  #      - name: Push to GitHub Packages
  #        id: docker_build
  #        uses: docker/build-push-action@v4
  #        with:
  #          build-args: |
  #            "USERNAME=${{ secrets.USERNAME }}"
  #            "TOKEN=${{ secrets.TOKEN }}"
  #          push: true
  #          tags: |
  #            ghcr.io/ing-sis-suarez/snippet-manager-dev:latest


  run_remote_script:
    name: Run remote script
    #    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #      - name: Create SSH key
      #        run: |
      #          mkdir -p ~/.ssh/
      #          echo "$SSH_PRIVATE_KEY" > ../private.key
      #          chmod 600 ../private.key
      #          ssh-keyscan ${{secrets.SSH_HOST_DEV}} >> ~/.ssh/known_hosts
      #        env:
      #          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: { %- raw -% } ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts

      - name: Run script on remote machine
        run: |
          ssh jorge@${{secrets.SSH_HOST_DEV}} "~/deploy.sh"